import { Inter } from "next/font/google";
import "./globals.css";

import NavBar from "@/components/NavBar/NarvBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden ${inter.className}`}>
        <div className="w-screen h-full overflow-x-hidden bg-gradient-to-b from-blue-50 to-red-100">
          <div className="h-24">
            <NavBar />
          </div>
          <div className="h-[calc(100vh - 96px)]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
